### ISSUE TITLE
Cleanup package folder

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-admin#16]
The algorithm of executing packages allows you to provide a **package name without the (zip) extension**. This is useful, because it lets us have packages as folders, without a zip file - take Admin\tools for example, a container that contains built-in tool folders, not zip files.

The problem with the current behavior is that if there is a **zip file and a folder with the same name**, SnAdmin uses the folder, even if the **zip package is newer**. This leads to a confusing install process (for example when we update a nuget package to a newer version that contains a new zip package).

**Solution**: if you execute the package with a name (without extension) and there is a zip file there, **we should always execute the zip file**. If a folder is there from a previous execution, than delete it before the operation.

**Comment by tusmester** [comment]
This deserves a _releasebloccker_ label because we should solve it before going _stable_ with the main components.

**Comment by kavics** [comment]
Agree
