### ISSUE TITLE
Package installation telemetry

### ISSUE THREAD

**Issue by tusmester** [SenseNet/sn-admin#17]
It would be cool if we added a **telemetry** layer to SnAdmin that would allow us to track what kind of packages are installed (similar to the install/download counter on nuget.org).

- When SnAdmin is executed, try to send some basic info to a central url about the package.
- Strictly **anonymous**, we do not want to know actually _who_ installed what, we just want to track package usage. 
- Store only:
  - package id
  - package version
  - install date
  - result (success/error)
- Only track 'official' sensenet ECM packages, not 3rd party ones.
- Clearly communicate this.
- Must be unobtrusive and robust - do not interfere with package execution in any way (e.g. send info in the background, not slowing down the execution process).

**Questions**

- opt in or opt out?

**Comment by kavics** [comment]
• Store only: 
o …
o success or not
